core/urls.py
from django.urls import path
from .views import (checkout_view, HomeView, BookDetailView, addBook_view, livre_view)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('checkout', checkout_view, name='checkout'),
    path('addbook', addBook_view, name='addbook'),
    path('l1', livre_view, name='l1'),
    path('book/<pk>/', BookDetailView.as_view(), name='book')
]

tradeholic/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.contrib.auth import get_user_model
from django.conf import settings
from django.db import models
from django.shortcuts import reverse

# Create your models here.


GENRE_CHOICES = (
    ("1", "Genre 1"),
    ("2", "Genre 2"),
    ("3", "Genre 3"),
    ("4", "Genre 4"),
    ("5", "Genre 5"),
    ("6", "Genre 6"),
    ("7", "Genre 7"),
    ("8", "Genre 8"),
    ("9", "Genre 9")
)


TRADETYPE_CHOICES = (
    ("S", "Sale"),
    ("T", "Trade"),
    ("G", "Giveaway")
)


class Book(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, null=False, blank=False)
    author = models.CharField(max_length=50)
    image = models.ImageField()
    genre = models.CharField(max_length=2, choices=GENRE_CHOICES)
    tradeType = models.CharField(max_length=1, choices=TRADETYPE_CHOICES)
    price = models.FloatField(null=True, blank=True)
    description = models.TextField(max_length=1000)
     
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("core:book", kwargs={"pk": self.pk})

core/forms.py
from allauth.account.forms import SignupForm,LoginForm
from django import forms
from .models import Book,GENRE_CHOICES,TRADETYPE_CHOICES

class Signup_Form(SignupForm):

    def __init__(self, *args, **kwargs):
        super(Signup_Form, self).__init__(*args, **kwargs)
        self.fields['username'].widget = forms.TextInput(attrs={
        'class': 'form-control',
        'name': 'username',
        'type': 'text',
        'id': 'form10'
        })
        self.fields['email'].widget = forms.EmailInput(attrs={
        'class': 'form-control',
        'name': 'email',
        'type': 'email',
        'id': 'form11'
        })
        self.fields['password1'].widget = forms.PasswordInput(attrs={
        'class': 'form-control',
        'name': 'password',
        'type': 'password',
        'id': 'form12'
        })


class Login_Form(LoginForm):

    def __init__(self, *args, **kwargs):
        super(Login_Form, self).__init__(*args, **kwargs)
        self.fields['login'].widget = forms.TextInput(attrs={
        'class': 'form-control',
        'name': 'login',
        'type': 'text',
        'id': 'form2'
        })
        self.fields['password'].widget = forms.PasswordInput(attrs={
        'class': 'form-control',
        'name': 'password',
        'type': 'password',
        'id': 'form8'
        })




class AddForm(forms.ModelForm):
    name = forms.CharField(max_length=50, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'name': 'bookname',
        'type': 'text',
        'id': 'bookname',
        'placeholder':'Nom du Livre'
        }))
    author = forms.CharField(max_length=50, widget=forms.TextInput(attrs={
        'class': 'form-control',
        'name': 'bookauthor',
        'type': 'text',
        'id': 'bookauthor',
        'placeholder':'Auteur du Livre'
        }))
    genre = forms.CharField(widget=forms.Select(choices=GENRE_CHOICES,attrs={
        'name':'bookgenre',
        'class':'browser-default custom-select'
    }))
    tradeType = forms.CharField(widget=forms.Select(choices=TRADETYPE_CHOICES,attrs={
        'name':'booktrade',
        'class':'browser-default custom-select'
    }))
    price = forms.FloatField( widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'name':'bookprice',
        'type': 'number',
        'id': 'bookprice',
        'placeholder':'Prix du Livre'
    }))
    image = forms.ImageField(widget=forms.ClearableFileInput(attrs={
        'style':"display:none;",
        'name':'bookimage',
        'id':'bookimage'
    }))
    description = forms.CharField(max_length=50, widget=forms.Textarea(attrs={
        'class':'form-control rounded-0',
        'name':'bookdesc',
        'type': 'text',
        'id': 'bookdescription',
        'placeholder':'Description du Livre'
    }))
    class Meta:
        model = Book
        fields = [
            'name',
            'author',
            'genre',
            'tradeType',
            'price',
            'image',
            'description'
        ]

core/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, View
from django.contrib.auth import authenticate, login, logout
from .filers import BookFilter

from django.conf import settings
from django.http import Http404

from .models import Book
from.forms import AddForm

# Create your views here.
class FilteredListView(ListView):
    filterset_class = BookFilter

    def get_queryset(self):
        # Get the queryset however you usually would.  For example:
        queryset = super().get_queryset()
        # Then use the query parameters and the queryset to
        # instantiate a filterset and save it as an attribute
        # on the view instance for later.
        self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
        # Return the filtered queryset
        return self.filterset.qs.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Pass the filterset to the template - it provides the form.
        context["filter"] = BookFilter(self.request.GET, queryset=self.get_queryset())
        return context

        
class HomeView(FilteredListView):
    model = Book
    paginate_by = 2
    template_name = "home.html"
    filterset_class = BookFilter
    


class BookDetailView(DetailView):
    model = Book
    template_name = "book.html"


def checkout_view(request):
    context = {
        'books' : Book.objects.all()
    }
    return render(request,'checkout.html',context)


def addBook_view(request):
    if not request.user.is_authenticated:
        raise Http404
    print(request.POST)
    if request.method == 'POST':
        print('aaaaaaaaaaaaaaaaaaaaaaaaa')
    form = AddForm(request.POST or None, request.FILES or None)
    if form.is_valid:
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        print('*****************************************************************')
    context = {
        'form' : form
    }
    return render(request,'addbook.html',context)


def livre_view(request):
    if not request.user.is_authenticated:
        raise Http404
    print(request.POST,'**********')
    if request.method == 'POST':
        print('aaaaaaaaaaaaaaaaaaaaaaaaa')
    form = AddForm(request.POST or None, request.FILES or None)
    if form.is_valid:
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        print('*****************************************************************')
        

    context = {
        'form' : form
    }
    return render(request,'l1.html',context)

templates/addbook.html
{% extends "account/base.html" %}

{% block content %}


<main>

  <!--Section: Products v.3-->
  <section class=" mb-4">

    <!--Grid row-->
    <div class="row wow fadeIn d-flex justify-content-center">

      <div class="col-lg-8 col-md-5">

        <!--Card-->
        <div class="card">

          <!--Card content-->
          <div class="card-body">

            <form method="POST" action="." enctype="multipart/form-data">
              {% csrf_token %}

              <div class="row d-flex align-items-center ">

                <div class="col-lg-6 col-md-6 d-flex flex-column">

                  <!-- Default input -->
                  <div class="form-group">
                    <label for="bookname">Nom du Livre:</label>
                    {{ form.name }}
                  </div>
                  <!-- Default input -->
                  <div class="form-group">
                    <label for="bookauthor">Auteur du Livre:</label>
                    {{ form.author }}
                  </div>
                  <div class="form-group">
                    <label for="bookauthor">Le genre du Livre:</label>
                    {{ form.genre }}
                  </div>
                  <div class="form-group">
                    <label for="bookauthor">Type déchange:</label>
                    {{ form.tradeType }}
                  </div>
                  <!-- Default input -->
                  <div class="form-group">
                    <label for="bookauthor">Prix:(Pour vente)</label>
                    {{ form.price }}
                  </div>

                </div>
                <div class="col-lg-6 col-md-6 d-flex flex-column">

                  <!-- Default input -->
                  <div class="form-group">
                    <label for="bookauthor">Description du Livre:</label>
                    {{ form.description }}
                  </div>
                  <button type="button" class="btn btn-outline-primary btn-rounded waves-effect"
                    onclick="document.getElementById('bookimage').click();">Photo du livre</button>

                  <div class="md-form ml-3 mr-4">
                    {{ form.image }}
                  </div>

                </div>
              </div>

                
                
                






              <div class="d-flex justify-content-center">
                <button class="btn btn-primary btn-sm " type="submit">Connection</button>
              </div>


            </form>

          </div>

        </div>
        <!--/Card-->

      </div>

    </div>
  </section>
  <!--Section: Products v.3-->

</main>






{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>
  {% block title %}{% endblock title %}
  </title>
    {% block extra_head %}
    {% endblock %}
  
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
</head>

<body class="grey lighten-3">

    <!-- Navbar -->
    {% include 'navbar.html' %}
    <!-- Navbar -->

  <div class="container mt-5 pt-4">
    {% block content %}
    {% endblock content %}
  </div>

  {% block extra_body %}
    {% endblock %}
    
    <!--Footer-->
    {% include 'footer.html' %}
    <!--/.Footer-->
    

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>
</body>

</html>

templates/book.html
{% extends 'base.html' %}


{% block title %}
  Product Page
{% endblock title %}
  

{% block content %}
  <!-- Navbar -->
  {% include 'navbar.html' %}
  <!-- Navbar -->
  
    <!--Main layout-->
    <main class="">
      <div class="container dark-grey-text mt-5">
  
        <!--Grid row-->
        <div class="row wow fadeIn">
  
          <!--Grid column-->
          <div class="col-md-6 mb-4">
  
            <img src="{{object.image.url}}" class="img-fluid" alt="">
  
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-md-6 mb-4">
  
            <!--Content-->
            <div class="p-4">

              
              {% if object.get_tradeType_display == "Sale" %}

              <div class="mb-3">
                <a href="">
                  <span class="badge purple mr-1">For Sale</span>
                </a>
              </div>

              <p>
                <span class="lead font-weight-bold">Titre: </span>
                <span>{{object.name}}</span>
              </p>

              <p>
                <span class="lead font-weight-bold">Auteur: </span>
                <span>{{object.author}}</span>
              </p>

              <p class="lead">
                <span class="lead font-weight-bold">Prix: </span>
                <span>{{object.price}}DT</span>
              </p>
  
              <p class="lead font-weight-bold">Description:</p>
  
              <p>{{object.description}}</p>

              {% else %}

              <div class="mb-3">
                <a href="">
                  <span class="badge purple mr-1">For {{object.get_tradeType_display}}</span>
                </a>
              </div>

              <p>
                <span class="lead font-weight-bold">Titre: </span>
                <span>{{object.name}}</span>
              </p>

              <p>
                <span class="lead font-weight-bold">Auteur: </span>
                <span>{{object.author}}</span>
              </p>

  
              <p class="lead font-weight-bold">Description:</p>
  
              <p>{{object.description}}</p>

              {% endif %}
                
  
              <form class="d-flex justify-content-left">
                <!-- Default input -->
                <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
                <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                  <i class="fas fa-shopping-cart ml-1"></i>
                </button>
  
              </form>
  
            </div>
            <!--Content-->
  
          </div>
          <!--Grid column-->
  
        </div>
        <!--Grid row-->
  
        <hr>
  
        <!--Grid row-->
        <div class="row d-flex justify-content-center wow fadeIn">
  
          <!--Grid column-->
          <div class="col-md-6 text-center">
  
            <h4 class="my-4 h4">Additional information</h4>
  
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
              voluptates,
              quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>
  
          </div>
          <!--Grid column-->
  
        </div>
        <!--Grid row-->
  
        <!--Grid row-->
        <div class="row wow fadeIn">
  
          <!--Grid column-->
          <div class="col-lg-4 col-md-12 mb-4">
  
            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">
  
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-lg-4 col-md-6 mb-4">
  
            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">
  
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-lg-4 col-md-6 mb-4">
  
            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">
  
          </div>
          <!--Grid column-->
  
        </div>
        <!--Grid row-->
  
      </div>
    </main>
    <!--Main layout-->
  
{% endblock content %}
  

templates/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% load bootstrap %}

{% block title %}
  Home Page
{% endblock title %}


{% block content %}





  <!--Main layout-->
  <main>

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5 ">


        <!-- Navbar brand -->
        <span class="navbar-brand">Filtres:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <form class="form-inline">
            <div class="md-form form-group my-0">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item">{{filter.form.name}}</li>
                <li class="nav-item">{{filter.form.genre}}</li>
                <li class="nav-item">{{filter.form.tradeType}}</li>
              </ul>
              <ul class="navbar-nav nav-flex-icons">
                <li class="nav-item"><button type="submit" class="btn btn-outline-light ml-auto p-2">Chercher</button></li>
              </ul>
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn ">
          
          
          {% for book in object_list %}
            <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4 d-flex align-items-stretch">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="{{book.image.url}}" class="card-img-top"
                  alt="{{book.image.name}}">
                <a href="{{ book.get_absolute_url }} ">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <h5>
                  <strong>
                    <a href="{{ book.get_absolute_url }} " class="dark-grey-text">{{book.name}}</a>
                  </strong>
                </h5>

                <h5 class="grey-text">{{book.author}}</h5>
                
                {% if book.get_tradeType_display == "Sale" %}
                <h5 class="grey-text">Price: </h5>
                <h4 class="font-weight-bold blue-text">
                  <strong>{{book.price}}DT</strong>
                </h4>
                {% else %}
                <h5 class="grey-text">{{book.get_tradeType_display}}</h5>
                {% endif %}

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->
          {% endfor %}
          


        </div>
        <!--Grid row-->

      </section>
      <!--Section: Products v.3-->
      {% load my_tags %}
      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">
          <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.previous_page_number}} " aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          {% endif %}   
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.previous_page_number}}">{{page_obj.previous_page_number}}</a>
          </li>
          {% endif %}
          <li class="page-item active">
            <a class="page-link" href="?page={{page_obj.number}}">{{page_obj.number}}
              <span class="sr-only">(current)</span>
            </a>
          </li>
          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}">{{page_obj.next_page_number}}</a>
          </li>
          {% endif %}   
          {% if page_obj.has_next %} 
          <li class="page-item">
            <a class="page-link" href="?page={{page_obj.next_page_number}}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
      <!--Pagination-->

  </main>
  <!--Main layout-->


{% endblock content %}

templates/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="#">
        <strong class="blue-text">𝓉𝓇𝒶𝒹𝑒𝐻𝒪𝐿𝐼𝒞</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="{% url 'core:home' %} ">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'core:checkout' %} ">Chekout</a>
          </li>
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">

          <hr>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %} ">
              <span > Lougout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %} ">
              <span> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %} ">
              <span> Signup </span>
            </a>
          </li>
          {% endif %}


        </ul>

      </div>

    </div>
  </nav>

templates/userbooks.html
{% extends 'base.html' %}


{% block title %}
  Product Page
{% endblock title %}
  

{% block content %}
  <!-- Navbar -->
  {% include 'navbar.html' %}
  <!-- Navbar -->
  
    <!--Main layout-->
    <main class="">
      <div class="container dark-grey-text mt-5">
  
        <!--Grid row-->
        <div class="row wow fadeIn">
  
          <!--Grid column-->
          <div class="col-md-6 mb-4">
  
            <img src="{{object.image.url}}" class="img-fluid" alt="">
  
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-md-6 mb-4">
  
            <!--Content-->
            <div class="p-4">

              
              {% if object.get_tradeType_display == "Sale" %}

              <div class="mb-3">
                <a href="">
                  <span class="badge purple mr-1">For Sale</span>
                </a>
              </div>

              <p>
                <span class="lead font-weight-bold">Titre: </span>
                <span>{{object.name}}</span>
              </p>

              <p>
                <span class="lead font-weight-bold">Auteur: </span>
                <span>{{object.author}}</span>
              </p>

              <p class="lead">
                <span class="lead font-weight-bold">Prix: </span>
                <span>{{object.price}}DT</span>
              </p>
  
              <p class="lead font-weight-bold">Description:</p>
  
              <p>{{object.description}}</p>

              {% else %}

              <div class="mb-3">
                <a href="">
                  <span class="badge purple mr-1">For {{object.get_tradeType_display}}</span>
                </a>
              </div>

              <p>
                <span class="lead font-weight-bold">Titre: </span>
                <span>{{object.name}}</span>
              </p>

              <p>
                <span class="lead font-weight-bold">Auteur: </span>
                <span>{{object.author}}</span>
              </p>

  
              <p class="lead font-weight-bold">Description:</p>
  
              <p>{{object.description}}</p>

              {% endif %}
                
  
              <form class="d-flex justify-content-left">
                <!-- Default input -->
                <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
                <button class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
                  <i class="fas fa-shopping-cart ml-1"></i>
                </button>
  
              </form>
  
            </div>
            <!--Content-->
  
          </div>
          <!--Grid column-->
  
        </div>
        <!--Grid row-->
  
        <hr>
  
        <!--Grid row-->
        <div class="row d-flex justify-content-center wow fadeIn">
  
          <!--Grid column-->
          <div class="col-md-6 text-center">
  
            <h4 class="my-4 h4">Additional information</h4>
  
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
              voluptates,
              quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>
  
          </div>
          <!--Grid column-->
  
        </div>
        <!--Grid row-->
  
        <!--Grid row-->
        <div class="row wow fadeIn">
  
          <!--Grid column-->
          <div class="col-lg-4 col-md-12 mb-4">
  
            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">
  
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-lg-4 col-md-6 mb-4">
  
            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">
  
          </div>
          <!--Grid column-->
  
          <!--Grid column-->
          <div class="col-lg-4 col-md-6 mb-4">
  
            <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">
  
          </div>
          <!--Grid column-->
  
        </div>
        <!--Grid row-->
  
      </div>
    </main>
    <!--Main layout-->
  
{% endblock content %}
  